#:schema node_modules/wrangler/config-schema.json
name = "shingleai-web"

main = "./workers/app.ts"
compatibility_date = "2025-04-22"
compatibility_flags = ["nodejs_compat"]
# tail_consumers = [{ service = "shingleai-web-tail" }]
# upload_source_maps = true
routes = [{ pattern = "www.shingleai.com", custom_domain = true }]
workers_dev = false
preview_urls = false

[observability]
enabled = true

# [assets]
# # https://developers.cloudflare.com/workers/static-assets/binding/
# directory = "./build/client"

# Bind a KV Namespace. Use KV as persistent storage for small key-value pairs.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#kv-namespaces
[[kv_namespaces]]
binding = "WEB_CACHE"
id = "f6acdf74227540fabeead83b8b03b9b3"

[[hyperdrive]]
binding = "HYPERDRIVE"
# id = "d116bed6d65146beb9922dd81963f8eb" # Direct
id = "566e70b3772d499aa0596b8e2ad9f2bd"                                          # Pooler
localConnectionString = "postgresql://postgres:postgres@localhost:5432/postgres"


[[queues.producers]]
queue = "workflows"
binding = "WORKFLOWS"

[[queues.producers]]
queue = "events"
binding = "EVENTS"
